# Generated by Django 5.0.1 on 2024-03-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_pet_order_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
