# Generated by Django 5.0.1 on 2024-03-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_order_final_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='camera',
        ),
        migrations.AddField(
            model_name='mobile',
            name='camera_setup',
            field=models.CharField(choices=[('One', 'Single'), ('Two', 'Double'), ('Three', 'Triple'), ('Four', 'Four')], default='Triple', max_length=20),
        ),
        migrations.AddField(
            model_name='mobile',
            name='is_5g_capable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobile',
            name='rear_camera',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='mobile',
            name='selfie_camera',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='mobile',
            name='colors',
            field=models.ManyToManyField(default='NA', to='core.color'),
        ),
    ]
