# Generated by Django 5.0.1 on 2024-03-15 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_color_remove_mobile_camera_mobile_camera_setup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.color'),
        ),
    ]
